name: Rust

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'what system the binary is for'
        required: false
        default: 'x86_64-unknown-linux-gnu'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          profile: minimal
          components: clippy
          target: ${{ inputs.target }}
          override: true
    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install pkg-config musl-tools libssl-dev
    - name: Build
      run: cargo build --release --target ${{ inputs.target }} --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.DEPLOY_TOKEN }}
        file: ./target/${{ inputs.target }}/release/reviews_widget
